app = "houda-app"  # اسم التطبيق بتاعك (اختياري، بيتحدد أوتوماتيك أول مرة)

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"  # Fly.io بيستخدم البورت 8080 افتراضيًا

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
